plugin: aws_ec2
regions:
  - us-east-1
hostnames:
  - tag:Name
  - ip-address
  - dns-name
# keyed_groups: << This is commented because it is not needed in this example, groups are defined below
#   - key: tags.OS
groups:
  AMZ_Linux_Client: "'AMZ_Linux' in tags.OS and 'Client' in tags.Ansible"
  Ubuntu_Client: "'Ubuntu' in tags.OS and 'Client' in tags.Ansible"
compose:
  ansible_host: private_ip_address